---
- name: Allow apt to download packages over https.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Install software-properties-common
  apt:
    name: 
    - software-properties-common
    - dirmngr
    state: present

- name: Install common packages
  apt:
    name: "{{ common_packages }}"
    state: present