---
- name: Allow apt to download packages over https.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  when: ansible_os_family == "Debian"

- name: Install software-properties-common
  apt:
    name: 
    - software-properties-common
    - dirmngr
    state: present
  when: ansible_os_family == "Debian"